package fr.sciforma.apietnic.business;

import lombok.Getter;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;
import java.util.ArrayList;
import java.util.List;

@Component
@Getter
public class ExtractorFactory {

    private List<SciformaField> jobClassificationFields;
    private List<SciformaField> laborAssignementFields;
    private List<SciformaField> organizationFields;
    private List<SciformaField> portfolioFolderFields;
    private List<SciformaField> projectFields;
    private List<SciformaField> resourceFields;
    private List<SciformaField> skillFields;
    private List<SciformaField> taskFields;
    private List<SciformaField> timesheetFields;
    private List<SciformaField> userFields;

    @PostConstruct
    public void init() {

        jobClassificationFields = new ArrayList<>();
        laborAssignementFields = new ArrayList<>();
        organizationFields = new ArrayList<>();
        portfolioFolderFields = new ArrayList<>();
        projectFields = new ArrayList<>();
        resourceFields = new ArrayList<>();
        skillFields = new ArrayList<>();
        taskFields = new ArrayList<>();
        timesheetFields = new ArrayList<>();
        userFields = new ArrayList<>();

        projectFields.add(SciformaField.builder().name("% Completed").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("%Ecart charge").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("%Ecart durée").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("%Ecart final").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("%Ecart prévision").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Active").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("Actual Labor Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Analyse avancement").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Analyse budget").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Approved").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("As of Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Avancement réel").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Avancement plannifié").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Baseline Duration").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Baseline Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline Labor Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline1 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline10 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline11 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline12 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline13 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline14 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline2 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline3 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline4 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline5 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline6 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline7 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline8 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline9 Saved Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_MCF_Charge_Annee_Courante").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Charge finale").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Charge réelle").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Charge restante").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Closed").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("Create Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Current Baseline").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Début réel").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Description").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Duration").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Ecart charge").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Ecart début").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Ecart durée").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Ecart fin").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Ecart final").type(FieldType.COST).build());
        projectFields.add(SciformaField.builder().name("Ecart prévision").type(FieldType.COST).build());
        projectFields.add(SciformaField.builder().name("Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Finish Constraint").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Hors-projet").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("ID").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Index Performance (TCPI)").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Index prévision (SPI)").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Initiator").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Internal ID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Labor ACWP").type(FieldType.COST).build());
        projectFields.add(SciformaField.builder().name("Labor BCWP").type(FieldType.COST).build());
        projectFields.add(SciformaField.builder().name("Labor BCWS").type(FieldType.COST).build());
        projectFields.add(SciformaField.builder().name("Manager 1").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Manager 2").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Manager 3").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Modified By").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Modified Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("N° ligne").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Portfolio Folder").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Published Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Ratio avancement").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Ratio ConsommationCharge Réelle/Finale").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Start Constraint").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Total Labor Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Version").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Version ID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Y_Analyste_Backup_nom").type(FieldType.RESOURCE).build());
        projectFields.add(SciformaField.builder().name("Y_Analyste_Backup_tel").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Analyste_nom").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Analyste_tel").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CatégorieAnalytique_projet").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Charge réf. 1").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Y_Charge réf. 2").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Y_Charge réf. 3").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Y_Charge réf. 4").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Y_Charge Ref 1").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Y_Charge Ref 2").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Y_Charge Ref 3").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Y_Charge Ref 4").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Y_charge_finale_réf1").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Y_ch_reelle_interprojet_PR").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Y_ch_restante_generique").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Y_CodeAnalytique_projet").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Commentaires").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Commentaire_Risque_Exogene").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CP_1_VAttribuee").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CP_1_VP").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CP_2_VAttribuee").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CP_2_VP").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CP_3_VAttribuee").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CP_3_VP").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Critere_utilite_1").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Critere_utilite_2").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Critere_utilite_3").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Critere_utilite_4").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Critere_utilite_5").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Critere_utilite_6").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Critere_utilite_7").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CU_1_VAttribuee").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CU_1_VP").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CU_2_VAttribuee").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CU_2_VP").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CU_3_VAttribuee").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CU_3_VP").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CU_4_VAttribuee").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CU_4_VP").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CU_5_VAttribuee").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CU_5_VP").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CU_6_VAttribuee").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CU_6_VP").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CU_7_VAttribuee").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_CU_7_VP").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CU_Poids1").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CU_Poids2").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CU_Poids3").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CU_Poids4").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CU_Poids5").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CU_Poids6").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CU_Poids7").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_DansContratAdministration").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("Y_DansProjetsStratégiquesCOSTRADI").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("Y_Date demande").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Date enreg. réf.").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Date fin").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Date statut demande ou projet").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Début réf. 1").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Début réf. 2").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Début réf. 3").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Début réf. 4").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Decision").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Décision_Risque_Exogene").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_DemandeurResp1").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_DemandeurResp2").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Demandeur_projet").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Documentation").type(FieldType.URL).build());
        projectFields.add(SciformaField.builder().name("Y_EstDeTypeET").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("Y_Etat demande ou projet").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Evalutation_Risque").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Fin réf. 1").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Fin réf. 2").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Fin réf. 3").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Fin réf. 4").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_GénériqueRéutilisable_projet").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("Y_IntégréRéférentiels_projet").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("Y_Libellé_projet").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_lot").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("Y_MCF_commentaires").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_MElissage").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Nature demande ou projet").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Nbr de coordination_support").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Nbr de demande").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Nbr de gestion_support").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Nbr de maintenance").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Nbr de projet").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Objectif fin").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Y_Ponderation_CU1").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Ponderation_CU2").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Ponderation_CU3").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Ponderation_CU4").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Ponderation_CU5").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Ponderation_CU6").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_Ponderation_CU7").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Y_PortéeTransversalité_projet").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Programme").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_ProgrammeListe_projet").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("#").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("% Completed").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("%Ecart charge").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("%Ecart durée").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("%Ecart final").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("%Ecart prévision").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Y_Act__externe").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("Closed").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("ACWP").type(FieldType.COST).build());
        projectFields.add(SciformaField.builder().name("Analyse avancement").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Analyse budget").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Avancement réel").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Avancement planifié").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Avt basé étapes").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("% Labor Effort Complete").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Avt Acquis").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("%Avt (Manuel)").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Avt théorique activité").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Baseline Duration").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Baseline Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline1 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline1 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline10 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline10 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline11 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline11 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline12 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline12 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline13 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline13 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline14 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline14 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline2 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline2 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline3 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline3 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline4 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline4 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline5 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline5 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline6 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline6 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline7 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline7 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline8 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline8 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline9 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline9 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Charge activité").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Charge finale Ress Sélectionnée").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Actual Labor Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline Labor Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Remaining Labor Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Charge restante Ress  Sélectionnée").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Description").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Duration").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Ecart").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("YY_Ecart (Etnic)").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Ecart charge").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Ecart début").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Ecart durée").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Ecart fin").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Ecart final").type(FieldType.COST).build());
        projectFields.add(SciformaField.builder().name("Ecart prévision").type(FieldType.COST).build());
        projectFields.add(SciformaField.builder().name("Fin année en cours").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Fin mois en cours").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Fin semaine en cours").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Fin semestre en cours").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Fin trimestre en cours").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("ID").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Index performance (TCPI)").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Index prévision (SPI)").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Internal ID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Is Parent").type(FieldType.BOOLEAN).build());
        projectFields.add(SciformaField.builder().name("Manager 1").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Manager 2").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Manager 3").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Performance").type(FieldType.DECIMAL).build());
        //projectFields.add(SciformaField.builder().name("Predecessor #s").type(FieldType.null).build());
        projectFields.add(SciformaField.builder().name("Ratio avancement").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Required Date").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Required Labor").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Resource #s").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Resource Names").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Ratio budget").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Start Delay").type(FieldType.DURATION).build());
        //projectFields.add(SciformaField.builder().name("Successor #s").type(FieldType.null).build());
        projectFields.add(SciformaField.builder().name("Total Float").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("E_TypeActivite").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Unités produites").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Version ID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("WBS").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Work Package ID").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Activité_est_un  lot").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Y_activité_lot").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_CodeAnalytique_lot").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Demandeur hérité/surchargé").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Y_Demandeur_lot").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Actual Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline1 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline1 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline1 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline10 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline10 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline10 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline11 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline11 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline11 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline12 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline12 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline12 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline13 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline13 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline13 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline14 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline14 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline14 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline2 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline2 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline2 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline3 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline3 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline3 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline4 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline4 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline4 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline5 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline5 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline5 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline6 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline6 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline6 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline7 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline7 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline7 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline8 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline8 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline8 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline9 Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Baseline9 Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Baseline9 Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Duration").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Effort % Complete").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("ID").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Job Classification").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Physical % Complete").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Project IID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Rate").type(FieldType.EFFORT_RATE).build());
        projectFields.add(SciformaField.builder().name("Remaining Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Resource IID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Skills").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Task IID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Version ID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Calendar").type(FieldType.CALENDAR).build());
        projectFields.add(SciformaField.builder().name("Compétence directe").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Compétences directes").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Internal ID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Job Classification").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Métier direct").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Skills").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("User Role").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Email Address 1").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("First Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Internal ID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Last Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Login ID").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Middle Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Organization").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Description").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Internal ID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Description").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Internal ID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Description").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Internal ID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Manager 1").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Manager 2").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Manager 3").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Organization Code").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Responsable 4").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Description").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Internal ID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Managers").type(FieldType.USER).build());
        projectFields.add(SciformaField.builder().name("Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Actual Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Actual Finish").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Actual Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Charge réelle (Approuvée)").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Charge réelle (Présentée)").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Charge réelle (Validée)").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Daily Notes").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Description").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Duration").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("ID").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Notes").type(FieldType.INTEGER).build());
        projectFields.add(SciformaField.builder().name("Project ID").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Project IID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Project Name").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Remaining Effort").type(FieldType.EFFORT).build());
        projectFields.add(SciformaField.builder().name("Remaining Estimate").type(FieldType.DURATION).build());
        projectFields.add(SciformaField.builder().name("Resource").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Resource IID").type(FieldType.DECIMAL).build());
        projectFields.add(SciformaField.builder().name("Resource Organization").type(FieldType.STRING).build());
        projectFields.add(SciformaField.builder().name("Start").type(FieldType.DATE).build());
        projectFields.add(SciformaField.builder().name("Task IID").type(FieldType.DECIMAL).build());

    }

}
